update

diff --git a/bin/winezgui b/bin/winezgui
--- a/bin/winezgui
+++ b/bin/winezgui
@@ -12,9 +12,10 @@ export APP_WITH_VER="${APPNAME}-${APPVERSION}"
 # Function Show help
 ShowHelp ()
 {
+  DBUG "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
   echo "WineZGUI - Wine GUI using Zenity "
   echo "Usage:"
-  echo "$0 <argument>"
+  echo "$(basename "${0}") <argument>"
   echo ""
   echo "Argument:"
   echo "exe/msi file      Creates prefix for the given exe file, else launch"
@@ -24,9 +25,9 @@ ShowHelp ()
   echo "-h, --help        Shows this help!"
   echo ""
   echo "Examples:"
-  echo "$0 setup.exe"
-  echo "$0 putty_installer.msi"
-  echo "$0 Notepadd.wzt"
+  echo "$(basename "${0}") setup.exe"
+  echo "$(basename "${0}") putty_installer.msi"
+  echo "$(basename "${0}") Notepadd.wzt"
 
 }
 
@@ -109,39 +110,39 @@ mkdir -p "${PREFIXES_DIR}"
 # If Settings.yml exists and debug: is set to true
 # If Settings.yml exists, get arch value from it: win32 or win64
 if [ -f "${SETTINGS_FILE}" ]; then
-     export WINEARCH=$(grep arch     ${SETTINGS_FILE}|cut -f2 -d ":")
+     export WINEARCH=$(grep arch    ${SETTINGS_FILE}|cut -f2 -d ":")
      export TEMPLATE=$(grep template ${SETTINGS_FILE}|cut -f2 -d ":")
      export DEBUG=$(grep debug ${SETTINGS_FILE}|cut -f2 -d ":")
-     export WineZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}"
+     export WINEZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}" 
      export TEMPLATE_NAME=$(basename ${TEMPLATE})
 fi
 
 # If Settings.yml does not exists, add arch:win64 and template:WineZGUI-win64
 if [ ! -f "${SETTINGS_FILE}" ] && [ -w ${WINEZGUIDIR} ]; then
      export WINEARCH="win64"
-     export WineZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}"
+     export WINEZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}" 
      DBUG "I: Winearch not defined in ${SETTINGS_FILE}; setting arch to win64"
      DBUG "I: Prefix template not defined in ${SETTINGS_FILE}"
-     DBUG "I: using ${WineZGUI_TEMPLATE}"
+     DBUG "I: using ${WINEZGUI_TEMPLATE}" 
      echo "arch:win64" >> "${SETTINGS_FILE}"
-     echo "template:${WineZGUI_TEMPLATE}" >> "${SETTINGS_FILE}"
-     export TEMPLATE="${WineZGUI_TEMPLATE}"
+     echo "template:${WINEZGUI_TEMPLATE}" >> "${SETTINGS_FILE}" 
+     export TEMPLATE="${WINEZGUI_TEMPLATE}" 
      export TEMPLATE_NAME=$(basename ${TEMPLATE})
 fi
 
 # If Settings.yml exists and arch: value do not match win32 or win64; use win64
-if [ "$WINEARCH" != "win32" ] && [ "$WINEARCH" != "win64" ] ; then
+if [ "$WINEARCH" != "win32" ] && [ "$WINEARCH" != "win64" ]; then
      export WINEARCH="win64"
      echo "E: arch:wine32/wine64 not found in ${SETTINGS_FILE}; using win64"
      echo "arch:win64" >> "${SETTINGS_FILE}"
-     export WineZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}"
+     export WINEZGUI_TEMPLATE="${TEMPLATES_DIR}/WineZGUI-${WINEARCH}" 
 fi
 
 # -- HANDLE Templates -- #
 # If Template Directory not found, set default to WineZGUI-win64 prefix template
 if [ ! -d "${TEMPLATE}" ]; then
-     sed "s|template:.*|template:${WineZGUI_TEMPLATE}|g" -i "${SETTINGS_FILE}"
-     export TEMPLATE="${WineZGUI_TEMPLATE}"
+     sed "s|template:.*|template:${WINEZGUI_TEMPLATE}|g" -i "${SETTINGS_FILE}" 
+     export TEMPLATE="${WINEZGUI_TEMPLATE}" 
      export TEMPLATE_NAME=$(basename ${TEMPLATE})
 fi
 
@@ -219,15 +220,17 @@ fi
 
 
 
-INITIALIZE_WINEPREFIX()
+Initialize_Wineprefix()
 {
-  if [ ! -f "${1}/Prefix_Initialized.txt" ] && [ $(which wine) ] ; then
-       DBUG "I: Startup: Initializing wine Prefix... arch is ${WINEARCH}"
+  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
+  DBUG "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
+  if [ ! -f "${1}/Prefix_Initialized.txt" ] && [ $(which wine) ]; then
+       DBUG "I: ${HEADER}: Initializing wine Prefix... arch is ${WINEARCH}"
        # Create Prefix then delete host linked directories
        WINEDLLOVERRIDES="mscoree,mshtml=" \
        WINEPREFIX=${1} \
        WINEDEBUG=-all \
-       ${WBOOT_CMD} 2>/dev/null
+      ${WBOOT_CMD} 2>/dev/null
 
        # Replace home liked directory links with normal directories
        # For Games which saves in ~/Documents now will save in
@@ -235,7 +238,7 @@ INITIALIZE_WINEPREFIX()
        SAVEIFS=${IFS}
        IFS=$(echo -en "\n\b")
 
-       DBUG "I: Startup: Removing symlinks from wineprefix"
+       DBUG "I: ${HEADER}: Removing symlinks from wineprefix"
 
        for i in $(find "${1}/drive_c/users/${USER}" -type l); do
               rm "${i}" && mkdir -p "${i}" && \
@@ -245,11 +248,11 @@ INITIALIZE_WINEPREFIX()
 
        # Create an empty file to test whether prefix is created
        touch "${1}/Prefix_Initialized.txt"
-       DBUG "I: Startup: Default Wine Prefix at ${1} Created"
+       DBUG "I: ${HEADER}: Default Wine Prefix at ${1} Created"
 
        # Create H: for HOME Directory for Wine Explorer
        ln -sf ${HOME} "${1}/dosdevices/h:"
-       DBUG "I: Startup: Created H: symlink to ${HOME}"
+       DBUG "I: ${HEADER}: Created H: symlink to ${HOME}"
   fi
 
 
@@ -273,113 +276,112 @@ INITIALIZE_WINEPREFIX()
        if ! [ -z "${FLATPAK_NAME}" ]; then  # If flatpak (variable has value)
        echo "Flatpak Name:${FLATPAK_NAME}"  >> "${ABOUTFILE}"
        fi
-       DBUG "I: Startup: Created ${ABOUTFILE}"
+       DBUG "I: ${HEADER}: Created ${ABOUTFILE}"
   fi
 }
 
 
 # Create wine template and link it to defaults
-# If Default (WineZGUI_TEMPLATE) is not found initialize it
-if [ ! -d "${WineZGUI_TEMPLATE}" ]; then
-     INITIALIZE_WINEPREFIX "${WineZGUI_TEMPLATE}"
+# If Default (WINEZGUI_TEMPLATE) is not found initialize it 
+if [ ! -d "${WINEZGUI_TEMPLATE}" ]; then 
+     Initialize_Wineprefix "${WINEZGUI_TEMPLATE}" 
 fi
 
 # Main WineZGUI application window function
 WineZGUI_Window()
 {
-     SELECTION=$(zenity --list --hide-header                      \
-                        --title "${APP_WITH_VER}"                 \
-                        --width=360 --height=440                  \
-                        --radiolist --column " "                  \
-                        --column "Action"                         \
-                            TRUE "Open Exe..."                    \
-                               0 "Launch..."                      \
-                               0 "Prefixes..."                   \
-                               0 "Backup..."                      \
-                               0 "Restore..."                     \
-                               0 "Delete..."                      \
-                               0 "Configure..."                   \
-                               0 "Settings..."                    \
-                               0 "Kill all..."                    \
-                               0 "More..."                        \
-                               0 "Help..."                        \
-                               0 "About..."                       \
-                               0 "Quit..."                        \
-                          --text "<b>Wine GUI using Zenity...</b>")
+  HEADER="$(basename ${0})"
+  SELECTION=$(zenity --list --hide-header                      \
+                     --title "${APP_WITH_VER}"                 \
+                     --width=360 --height=440                  \
+                     --radiolist --column " "                  \
+                     --column "Action"                         \
+                         TRUE "Open Exe..."                    \
+                            0 "Launch..."                      \
+                            0 "Prefixes..."                   \
+                            0 "Backup..."                      \
+                            0 "Restore..."                     \
+                            0 "Delete..."                      \
+                            0 "Template..."                   \
+                            0 "Settings..."                    \
+                            0 "Kill all..."                    \
+                            0 "More..."                        \
+                            0 "Help..."                        \
+                            0 "About..."                       \
+                            0 "Quit..."                        \
+                       --text "<b>Wine GUI using Zenity...</b>")
 
-     # Exit if Cancel is clicked
-     if [ -z "${SELECTION}" ] ; then
-          DBUG "I: Cancel Selected. Bye!"
-          exit 0
-     fi
+  # Exit if Cancel is clicked
+  if [ -z "${SELECTION}" ]; then
+       DBUG "I: ${HEADER}: Cancel Selected. Bye!"
+       exit 0
+  fi
 
-     # Show What is selected     
-     DBUG "I: ${SELECTION} Selected!"
+  # Show What is selected     
+  DBUG "I: ${HEADER}: ${SELECTION} Selected!"
 
-     if   [ "${SELECTION}" = "Open Exe..." ]; then
-            source ${DATADIR}/winezgui-open-exe
-            WineZGUI_Open_Exe
+  if   [ "${SELECTION}" = "Open Exe..." ]; then
+         source ${DATADIR}/winezgui-open-exe 
+         WineZGUI_Open_Exe
 
-     elif [ "${SELECTION}" = "Launch..."  ]; then
-            source ${DATADIR}/winezgui-launch
-            WineZGUI_Launch
-            
-     elif [ "${SELECTION}" = "Prefixes..."  ]; then
-            source ${DATADIR}/winezgui-prefixes
-            WineZGUI_Prefixes
-            
-     elif [ "${SELECTION}" = "Backup..." ]; then
-            source ${DATADIR}/winezgui-backup
-            WineZGUI_Backup
-            
-     elif [ "${SELECTION}" = "Restore..." ]; then
-            source ${DATADIR}/winezgui-restore
-            WineZGUI_Restore
-            
-     elif [ "${SELECTION}" = "Configure..." ]; then
-            source ${DATADIR}/winezgui-configure
-            WineZGUI_Configure
-            
-     elif [ "${SELECTION}" = "Settings..."  ]; then
-            source ${DATADIR}/winezgui-settings
-            WineZGUI_Settings
-            
-     elif [ "${SELECTION}" = "More..."  ]; then
-            source ${DATADIR}/winezgui-more
-            WineZGUI_More
-            
-     elif [ "${SELECTION}" = "Delete..."  ]; then
-            source ${DATADIR}/winezgui-delete-prefix
-            WineZGUI_Delete_Prefix
-            
-     elif [ "${SELECTION}" = "Help..." ]; then
-            source ${DATADIR}/winezgui-help
-            WineZGUI_Help
-            
-     elif [ "${SELECTION}" = "About..." ]; then
-            source ${DATADIR}/winezgui-about
-            WineZGUI_About
-            
-     elif [ "${SELECTION}" = "Kill all..." ]; then
-            source ${DATADIR}/winezgui-kill-all
-            WineZGUI_Kill_All
-            
-     elif [ "${SELECTION}" = "Quit..." ]; then
-            source ${DATADIR}/winezgui-quit
-            WineZGUI_Quit
-     fi
-     
-     # After All options 
-     WineZGUI_Window
+  elif [ "${SELECTION}" = "Launch..."  ]; then
+         source ${DATADIR}/winezgui-launch 
+         WineZGUI_Launch
+         
+  elif [ "${SELECTION}" = "Prefixes..."  ]; then
+         source ${DATADIR}/winezgui-prefixes 
+         WineZGUI_Prefixes
+         
+  elif [ "${SELECTION}" = "Backup..." ]; then
+         source ${DATADIR}/winezgui-backup 
+         WineZGUI_Backup
+         
+  elif [ "${SELECTION}" = "Restore..." ]; then
+         source ${DATADIR}/winezgui-restore 
+         WineZGUI_Restore
+         
+  elif [ "${SELECTION}" = "Template..." ]; then
+         source ${DATADIR}/winezgui-template 
+         WineZGUI_Template
+
+  elif [ "${SELECTION}" = "Settings..."  ]; then
+         source ${DATADIR}/winezgui-settings 
+         WineZGUI_Settings
+         
+  elif [ "${SELECTION}" = "More..."  ]; then
+         source ${DATADIR}/winezgui-more 
+         WineZGUI_More
+         
+  elif [ "${SELECTION}" = "Delete..."  ]; then
+         source ${DATADIR}/winezgui-delete-prefix 
+         WineZGUI_Delete_Prefix
+         
+  elif [ "${SELECTION}" = "Help..." ]; then
+         source ${DATADIR}/winezgui-help 
+         WineZGUI_Help
+         
+  elif [ "${SELECTION}" = "About..." ]; then
+         source ${DATADIR}/winezgui-about 
+         WineZGUI_About
+         
+  elif [ "${SELECTION}" = "Kill all..." ]; then
+         source ${DATADIR}/winezgui-kill-all 
+         WineZGUI_Kill_All
+         
+  elif [ "${SELECTION}" = "Quit..." ]; then
+         source ${DATADIR}/winezgui-quit 
+         WineZGUI_Quit
+  fi
+  
+  # After All options 
+  WineZGUI_Window
 } # END of "Start WineZGUI window when no argument is supplied" section
 
 #------------------------------- Startup -----------------------------#
-# on launch, if no argument is provided
-if [ $# -eq 0  ]; then
-     DBUG "I: Startup: No arguments supplied..."
-else
-
-     DBUG "I: Startup: Checking ${EXE_FILE}"
+# If 1 arugment is given, i.e., >0 and <2 = 1
+if [ $# -gt 0 ] && [ $# -lt 2 ]; then
+     HEADER="$(basename ${0})"
+     DBUG "I: ${HEADER}: Startup: Checking ${1}"
      EXE_FILE="$(realpath -m "${1}")"
      EXE_NAME=$(basename "${EXE_FILE}")
      EXE_PATH=$(dirname  "${EXE_FILE}")
@@ -397,12 +399,13 @@ else
      IS_EXE="$(echo ${EXE_EXT}|tr A-Z a-z)"
 
      # Check if the argument is exe or msi or wzt
-     if [ "${IS_EXE}" != "exe" ] && [ "${IS_EXE}" != "msi" ] && \
-        [ "${IS_EXE}" != "wzt" ] ; then
+     if [ "${IS_EXE}" != "exe" ] && \
+        [ "${IS_EXE}" != "msi" ] && \
+        [ "${IS_EXE}" != "wzt" ]; then
 
-          echo "E: Startup: \"${EXE_NAME}\" is not an EXE file"
-          Mesg "I: Startup: Please provide an exe, msi, or a wzt file..."
-          DBUG "I: Startup: Exiting..."
+          echo "E: ${HEADER}: Startup: \"${EXE_NAME}\" is not an EXE file"
+          Mesg "I: ${HEADER}: Startup: Please give an exe, msi, or a wzt file."
+          DBUG "I: ${HEADER}: Startup: Exiting..."
           exit 1
 
      fi
@@ -410,74 +413,81 @@ fi
 
 ## On 1st launch create default wine prefix
 ### Create a default wine prefix directory ###
-if ! [ -d "${WineZGUI_TEMPLATE}" ]; then
-     DBUG "I: Startup: ${WineZGUI_TEMPLATE} does not exist, creating.."
-     mkdir -p "${WineZGUI_TEMPLATE}"
+if ! [ -d "${WINEZGUI_TEMPLATE}" ]; then 
+     DBUG  "I: ${HEADER}: ${WINEZGUI_TEMPLATE} does not exist, creating..." 
+     mkdir -p "${WINEZGUI_TEMPLATE}" 
 fi
 
 # ====================== Open EXE ================================= #
-OPEN_EXE_FUNCTION(){
-     if [ -f "${EXE_FILE}"  ] ; then
+Open_Exe()
+{
+  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
+  DBUG "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
+  if ! [ -f "${EXE_FILE}"  ]; then
+       echo "E: ${HEADER}: Cannot find ${EXE_FILE}, exiting!"
+       exit 1
+  fi
 
-          if [ "${IS_EXE}" = "wzt" ]; then
-               export WZT_FILE="${EXE_FILE}"
-               DBUG "I: Startup: WineZGUI Backup file submitted"
-               source ${DATADIR}/winezgui-backup-restore-function
-               source ${DATADIR}/winezgui-restore-wzt
-               Restore_Wzt_File
-               DBUG "I: Startup: Exiting main program after restoring backup"
-               exit 0;
-          fi
-          DBUG "I: Open EXE: exe is ${EXE_FILE}"
-          # Prompt to Launch exe with default or existing Prefix of that exe
-          EXE_FILE=$(realpath -m "${EXE_FILE}")
-          EXE_NAME=$(basename    "${EXE_FILE}")
-          EXE_PATH=$(dirname     "${EXE_FILE}")
-          EXE_NOSP=$(echo ${EXE_NAME} |tr " " "_");
-          EXE_LESS=$(echo ${EXE_NOSP}|sed "s/\.[Ee][Xx][Ee]//" \
-               |sed "s/\.[Mm][Ss][Ii]//")
-          EXE_EXT="${EXE_FILE##*.}"
-          WINEPREFIX_SUBDIR="${PREFIXES_DIR}/${EXE_LESS}"
-          # If existing prefix exists for the exe
-          SCRIPT_TO_RUN="${WINEZGUIDIR}/${EXE_LESS}/${EXE_LESS}.sh"
-          DEBUG="y"
-          DBUG "SCRIPT_TO_RUN $SCRIPT_TO_RUN"
-          unset DEBUG
-          if [ -f  "${SCRIPT_TO_RUN}" ] ; then
-               DBUG "I:OE: Prefix found for ${EXE_NAME}! Launching..."
-               
-               "${SCRIPT_TO_RUN}" # Run the script file associated with the exe
+  if [ "${IS_EXE}" = "wzt" ]; then
+       export WZT_FILE="${EXE_FILE}"
+       DBUG "I: ${HEADER}: WineZGUI Backup file submitted"
+       source ${DATADIR}/winezgui-backup-restore-function 
+       source ${DATADIR}/winezgui-restore-wzt 
+       Restore_Wzt_File
+       DBUG "I: ${HEADER}: Exiting main program after restoring backup"
+       exit 0;
+  fi
+  DBUG "I: ${HEADER}: File is ${EXE_FILE}"
+  # Prompt to Launch exe with default or existing Prefix of that exe
+  EXE_FILE=$(realpath -m "${EXE_FILE}")
+  EXE_NAME=$(basename    "${EXE_FILE}")
+  EXE_PATH=$(dirname     "${EXE_FILE}")
+  EXE_NOSP=$(echo ${EXE_NAME}|tr " " "_");
+  EXE_LESS=$(echo ${EXE_NOSP}|sed "s/\.[Ee][Xx][Ee]//"|sed "s/\.[Mm][Ss][Ii]//")
+  EXE_EXT="${EXE_FILE##*.}"
+  WINEPREFIX_SUBDIR="${PREFIXES_DIR}/${EXE_LESS}"
+  # If existing prefix exists for the exe
+  SCRIPT_TO_RUN="${WINEPREFIX_SUBDIR}/${EXE_LESS}.sh"
+  
+  DBUG "I: ${HEADER}: Script to check = $SCRIPT_TO_RUN"
+  
+  if [ -f  "${SCRIPT_TO_RUN}" ]; then
+       DBUG "I: ${HEADER}: Prefix found for ${EXE_NAME}! Launching..."
+       
+       "${SCRIPT_TO_RUN}" # Run the script file associated with the exe
 
-               # If open exe closes/deleted/cancelled by user from winezgui,
-               #  continue with winezgui, this is more of an expected behavior
-               DBUG "I: Open EXE: Re-Launching Main function after ${EXE_LESS}.sh"
-               WineZGUI_Window
+       # If open exe closes/deleted/cancelled by user from winezgui,
+       #  continue with winezgui, this is more of an expected behavior
+       DBUG "I: ${HEADER}: Re-Launching WineZGUI_Window after ${EXE_LESS}.sh"
+       WineZGUI_Window
 
-          else
-               DBUG "I: Open EXE: Creating Prefix for ${EXE_FILE}"
-               ${DATADIR}/winezgui-create-prefix "${EXE_FILE}"
-               # Launch after creating new prefix
-               DBUG "I: Open EXE: Created Script:" \
-                    "${WINEPREFIX_SUBDIR}/${EXE_LESS}.sh"
-               DBUG "I: Open EXE: Created Script: Launching ${EXE_LESS}.sh"
-               ${WINEPREFIX_SUBDIR}/"${EXE_LESS}.sh"
+  else
+       DBUG "I: ${HEADER}: Creating Prefix for ${EXE_FILE}"
+      ${DATADIR}/winezgui-create-prefix "${EXE_FILE}"
+       # Launch after creating new prefix
+       DBUG "I: ${HEADER}: Created Script:" \
+            "${WINEPREFIX_SUBDIR}/${EXE_LESS}.sh"
+       DBUG "I: ${HEADER}: Created Script: Launching ${EXE_LESS}.sh"
+      ${WINEPREFIX_SUBDIR}/"${EXE_LESS}.sh"
 
-               # Exit after script file is created
-               echo "WineZGUI !!!not!!! Exiting after launching ${EXE_LESS}.sh..."
-               #exit 0
-               WineZGUI_Window
-          fi
-     fi
+       WineZGUI_Window
+  fi
+
 }
 
 # Initialize Wineprefix for use
-INITIALIZE_WINEPREFIX "${WineZGUI_TEMPLATE}"
+Initialize_Wineprefix "${WINEZGUI_TEMPLATE}" 
 
 # Start WineZGUI when no argument is supplied
-if [ $# -eq 0 ] ; then
-     DBUG "I: Startup: Launching WineZGUI"
-     WineZGUI_Window
+if   [ $# -eq 0 ]; then
+       DBUG "I: ${HEADER}: Launching WineZGUI"
+       WineZGUI_Window
+elif [ $# -gt 1 ]; then
+       echo "E: ${HEADER}: WineZGUI accepts only 1 argument. It can be an exe, wzt or msi file."
+       echo "${0} --help"
+       ShowHelp
+       exit 1
 fi
 # Open exe function handles exe argument
-OPEN_EXE_FUNCTION
+Open_Exe
 
