Recreate All Scripts -> Ask whether to use existing Shorcut Name and Icon

diff --git a/resources/modules/winezgui-recreate-prefix-script b/resources/modules/winezgui-recreate-prefix-script
--- a/resources/modules/winezgui-recreate-prefix-script
+++ b/resources/modules/winezgui-recreate-prefix-script
@@ -172,67 +172,81 @@ if [ ! -d "${PREFIXDIR}" ]; then
 
 fi
 
-# Extract icon and convert it to several png files of diferent quality,
-# Create a temporary Directory to extract icon from the exe file
-DBUG "I: ${HEADER}: Icon: Extraction from ${EXE_NAME}"
-mkdir -p ${TEMPDIR} && \
-DBUG "I: ${HEADER}: Icon: Created directory ${TEMPDIR}"
-cd ${TEMPDIR}
 
-# wrestool extracts ico file from EXE
-${WRESTOOL_CMD} -x -t 14 "${EXE_FILE}" > "${TEMPDIR}/${EXE_LESS}.ico" 2> /dev/null && \
-DBUG "I: ${HEADER}: Icon: Wrestool executed"
+# Ask user whether to use existing name and icon
+unset TITLE TEXT
+TITLE="Recreate All Scripts"
+TEXT="Use existing Name and Icon?"
+${ZENITY_CMD} --question --title "${TITLE}" --text "$TEXT"
 
-# Only try to extract Icon when Icon is Found in the EXE
-# icotool extracts all png files from ico files
-# Select and copy the best png image file by sorting using ls -S1.
-${ICOTOOL_CMD} -x "${TEMPDIR}/${EXE_LESS}.ico" 2>/dev/null && \
-DBUG "I: ${HEADER}: Icotool: Extracting png files from" "${EXE_LESS}.ico" && \
-cp $(ls -S -1 ${TEMPDIR}/${EXE_LESS}*.png  | head -n 1) ${ICON} && \
-DBUG "I: ${HEADER}: Icon: Copied successfully..." && WARN="false"
+ANSWER=$?
+unset TITLE TEXT
 
-# If icon could not be copied, warn the user
-if [ "${WARN}" != "false" ]; then
-     DBUG "I: ${HEADER}: Icon could not be copied..." \
-          "use \"Change Icon...\" option"
+if [ ${ANSWER} -eq 1 ] ; then
+     # Extract icon and convert it to several png files of diferent quality,
+     # Create a temporary Directory to extract icon from the exe file
+     DBUG "I: ${HEADER}: Icon: Extraction from ${EXE_NAME}"
+     mkdir -p ${TEMPDIR} && \
+     DBUG "I: ${HEADER}: Icon: Created directory ${TEMPDIR}"
+     cd ${TEMPDIR}
+
+     # wrestool extracts ico file from EXE
+     ${WRESTOOL_CMD} -x -t 14 "${EXE_FILE}" > "${TEMPDIR}/${EXE_LESS}.ico" 2> /dev/null && \
+     DBUG "I: ${HEADER}: Icon: Wrestool executed"
+
+     # Only try to extract Icon when Icon is Found in the EXE
+     # icotool extracts all png files from ico files
+     # Select and copy the best png image file by sorting using ls -S1.
+     ${ICOTOOL_CMD} -x "${TEMPDIR}/${EXE_LESS}.ico" 2>/dev/null && \
+     DBUG "I: ${HEADER}: Icotool: Extracting png files from" "${EXE_LESS}.ico" && \
+     cp $(ls -S -1 ${TEMPDIR}/${EXE_LESS}*.png  | head -n 1) ${ICON} && \
+     DBUG "I: ${HEADER}: Icon: Copied successfully..." && WARN="false"
+
+     # If icon could not be copied, warn the user
+     if [ "${WARN}" != "false" ]; then
+          DBUG "I: ${HEADER}: Icon could not be copied..." \
+               "use \"Change Icon...\" option"
+     fi
+
+     # Cleanup tempdir and clear variable
+     unset WARN
+
+     #remove tmp directory after copying icon png
+     rm -rf "${TEMPDIR}" && \
+     DBUG "I: ${HEADER}: Icon: Cleanup ${TEMPDIR}"
+
+
+
+     # Prepare Desktop file
+     APP_CATEGORY="Game"
+     DBUG "I: ${HEADER}: Setting Category - ${APP_CATEGORY}"
+
+     # Create Desktop Shortcut
+     echo '`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`'
+     echo "EXE FILE = ${EXE_FILE}"
+     echo "EXIFTOOL = ${EXIFTOOL}"
+     DBUG "I: ${HEADER}: Name: Program Name Detection from exe file"
+     # Automatically set name, read from pe file, if not found use exe name
+     PRODUCT=$(${EXIFTOOL} "${EXE_FILE}"|grep -i "product name"|cut -f2 -d ":" \
+                                                            |sed "s/^ //")
+     # if language is not english inside exe name, or product is "", use exe name
+     if [ $(echo ${PRODUCT} | grep -aEv [a-zA-Z] ) ] || [ -z "${PRODUCT}" ]; then
+          unset PRODUCT
+          unset PROGNAME
+          # PROGNAME=$(echo "${EXE_NAME} (${APP_WITH_VER})"|sed "s/\.[mM][Ss][Ii]//g"\
+
+          PROGNAME=$(echo "${EXE_NAME}"                  |sed "s/\.[mM][Ss][Ii]//g"\
+                                                       |sed "s/\.[eE][Xx][Ee]//g");
+          DBUG "I: ${HEADER}: Name: Product Name not found, using exe name"
+     else
+          #PROGNAME=$(echo "${PRODUCT} (${APP_WITH_VER})");
+          PROGNAME=$(echo "${PRODUCT}");
+          DBUG "I: ${HEADER}: Name: Product Name found: \"${PRODUCT}\""
+     fi
 fi
-
-# Cleanup tempdir and clear variable
-unset WARN
-
-#remove tmp directory after copying icon png
-rm -rf "${TEMPDIR}" && \
-DBUG "I: ${HEADER}: Icon: Cleanup ${TEMPDIR}"
-
-
-
-# Prepare Desktop file
-APP_CATEGORY="Game"
-DBUG "I: ${HEADER}: Setting Category - ${APP_CATEGORY}"
-
-# Create Desktop Shortcut
-echo '`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`'
-echo "EXE FILE = ${EXE_FILE}"
-echo "EXIFTOOL = ${EXIFTOOL}"
-DBUG "I: ${HEADER}: Name: Program Name Detection from exe file"
-# Automatically set name, read from pe file, if not found use exe name
-PRODUCT=$(${EXIFTOOL} "${EXE_FILE}"|grep -i "product name"|cut -f2 -d ":" \
-                                                          |sed "s/^ //")
-# if language is not english inside exe name, or product is "", use exe name
-if [ $(echo ${PRODUCT} | grep -aEv [a-zA-Z] ) ] || [ -z "${PRODUCT}" ]; then
-     unset PRODUCT
-     unset PROGNAME
-     # PROGNAME=$(echo "${EXE_NAME} (${APP_WITH_VER})"|sed "s/\.[mM][Ss][Ii]//g"\
-
-     PROGNAME=$(echo "${EXE_NAME}"                  |sed "s/\.[mM][Ss][Ii]//g"\
-                                                    |sed "s/\.[eE][Xx][Ee]//g");
-     DBUG "I: ${HEADER}: Name: Product Name not found, using exe name"
-else
-     #PROGNAME=$(echo "${PRODUCT} (${APP_WITH_VER})");
-     PROGNAME=$(echo "${PRODUCT}");
-     DBUG "I: ${HEADER}: Name: Product Name found: \"${PRODUCT}\""
-fi
-
+echo "==========================="
+     echo "PROGNAME=$PROGNAME"
+     echo "ICON=$ICON"
 
 # Generate Sha256sum for the exefile
 CHECKSUM=$(sha256sum "${EXE_FILE}"|cut -f1 -d " ")
